# frontend-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: samikshav/full-stack-app-frontend:latest
          ports:
            - containerPort: 3000

---
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30036  # Access via <NodeIP>:30036
