name: CI/CD - Docker Compose to K8s via EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  FRONTEND_IMAGE: samikshav/full-stack-app-frontend:latest
  BACKEND_IMAGE: samikshav/full-stack-app-backend:latest
  KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE ./docker/frontend
          docker push $FRONTEND_IMAGE

      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE ./docker/backend
          docker push $BACKEND_IMAGE

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy kubeconfig from EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/etc/rancher/k3s/k3s.yaml $KUBECONFIG
          sed -i "s/127.0.0.1/${{ secrets.EC2_PUBLIC_IP }}/g" $KUBECONFIG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl --kubeconfig=$KUBECONFIG apply -f ./k8s
