name: CI/CD - Docker Compose to K8s via EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  FRONTEND_IMAGE: samikshav/full-stack-app-frontend:latest
  BACKEND_IMAGE: samikshav/full-stack-app-backend:latest
  KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker & Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 🔧 Build & Push Docker Images
        run: |
          docker build -t $FRONTEND_IMAGE ./docker/frontend
          docker push $FRONTEND_IMAGE
          docker build -t $BACKEND_IMAGE ./docker/backend
          docker push $BACKEND_IMAGE

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🧱 Setup & Apply Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🚀 Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: 🔑 Save EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: 📦 Retrieve kubeconfig from EC2
        run: |
          for i in {1..12}; do
            scp -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/kubeconfig.yaml kubeconfig.yaml && break
            echo "⏳ Waiting for kubeconfig.yaml..."; sleep 10;
          done
          if [ ! -f kubeconfig.yaml ]; then
            echo "❌ kubeconfig.yaml not found on EC2"; exit 1;
          fi
          sed -i "s/127.0.0.1/${{ secrets.EC2_PUBLIC_IP }}/g" kubeconfig.yaml
          echo "✅ kubeconfig.yaml copied and updated."

      - name: ⚙️ Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: 🚢 Deploy to Kubernetes
        run: |
          sudo yum install -y git
          git clone https://github.com/Samiksha998/project.git
          cd project
          kubectl --kubeconfig=../kubeconfig.yaml apply -f ./k8smanifests

