name: CI/CD - K8s Deploy via Terraform

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  FRONTEND_IMAGE: samikshav/full-stack-app-frontend:latest
  BACKEND_IMAGE: samikshav/full-stack-app-backend:latest
  KUBECONFIG_FILE: kubeconfig.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.samikshav }}
        password: ${{ secrets.Samiksha@1998 }}

    - name: Build & Push Frontend Image
      run: |
        docker build -t $FRONTEND_IMAGE ./frontend
        docker push $FRONTEND_IMAGE

    - name: Build & Push Backend Image
      run: |
        docker build -t $BACKEND_IMAGE ./backend
        docker push $BACKEND_IMAGE

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > $KUBECONFIG_FILE
        export KUBECONFIG=$KUBECONFIG_FILE

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s-code
