name: CI/CD - Docker Compose to K8s via EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  FRONTEND_IMAGE: samikshav/full-stack-app-frontend:latest
  BACKEND_IMAGE: samikshav/full-stack-app-backend:latest
  KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE ./docker/frontend
          docker push $FRONTEND_IMAGE

      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE ./docker/backend
          docker push $BACKEND_IMAGE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install K3s on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            curl -sfL https://get.k3s.io | sh -
            sudo cp /etc/rancher/k3s/k3s.yaml /home/ec2-user/k3s.yaml
            sudo chown ec2-user:ec2-user /home/ec2-user/k3s.yaml
          EOF

      - name: Copy kubeconfig from EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/k3s.yaml $KUBECONFIG
          sed -i "s/127.0.0.1/${{ secrets.EC2_PUBLIC_IP }}/g" $KUBECONFIG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl --kubeconfig=$KUBECONFIG apply -f ./k8smanifests
